package nosql

const (
	AND       = "$and"
	IN        = "$in"
	NIN       = "$nin"
	SET       = "$set"
	ADDTOSET  = "$addToSet"
	EQ        = "$eq"
	NE        = "$ne"
	GT        = "$gt"
	GTE       = "$gte"
	LT        = "$lt"
	LTE       = "$lte"
	REGEX     = "$regex"
	Options   = "$options"
	OR        = "$or"
	All       = "$all"
	EACH      = "$each"
	Slice     = "$slice"
	ElemMatch = "$elemMatch"
	PULL      = "$pull"
	PullAll   = "$pullAll"
	Unset     = "$unset"
	PUSH      = "$push"
	INC       = "$inc"
	Exists    = "$exists"
	Position  = "$position"
	Add       = "$add"
	Lockup    = "$lookup"
	Expr      = "$expr"
	First     = "$first"
	Hour      = "$hour"
	Cond      = "$cond"
	Remove    = "$$REMOVE"
	Match     = "$match"
	Unwind    = "$unwind"
	Project   = "$project"
	Bucket    = "$bucket"
	Group     = "$group"
)
