// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package biz

import (
	"github.com/go-kratos/kratos/v2/log"
	"os"
)

// Injectors from wire.go:

func newBiz(repo GreeterRepo) (*GreeterUsecase, error) {
	writer := _wireFileValue
	logger := log.NewStdLogger(writer)
	greeterUsecase := NewGreeterUsecase(repo, logger)
	return greeterUsecase, nil
}

var (
	_wireFileValue = os.Stdout
)
